INSERT INTO public.categories ("name") VALUES
	 ('Electronics 1'),
	 ('Clothing 1'),
	 ('Books 1'),
	 ('Home Decor 1'),
	 ('Beauty 1'),
	 ('Fitness 1'),
	 ('Toys 1'),
	 ('Groceries 1'),
	 ('Shoes 1'),
	 ('Accessories 1');
INSERT INTO public.categories ("name") VALUES
	 ('Electronics 2'),
	 ('Clothing 2'),
	 ('Books 2'),
	 ('Home Decor 2'),
	 ('Beauty 2'),
	 ('Fitness 2'),
	 ('Toys 2'),
	 ('Groceries 2'),
	 ('Shoes 2'),
	 ('Accessories 2');
INSERT INTO public.categories ("name") VALUES
	 ('Electronics 3'),
	 ('Clothing 3'),
	 ('Books 3'),
	 ('Home Decor 3'),
	 ('Beauty 3'),
	 ('Fitness 3'),
	 ('Toys 3'),
	 ('Groceries 3'),
	 ('Shoes 3'),
	 ('Accessories 3');
INSERT INTO public.categories ("name") VALUES
	 ('Electronics 4'),
	 ('Clothing 4'),
	 ('Books 4'),
	 ('Home Decor 4'),
	 ('Beauty 4'),
	 ('Fitness 4'),
	 ('Toys 4'),
	 ('Groceries 4'),
	 ('Shoes 4'),
	 ('Accessories 4');
INSERT INTO public.categories ("name") VALUES
	 ('Electronics 5'),
	 ('Clothing 5'),
	 ('Books 5'),
	 ('Home Decor 5'),
	 ('Beauty 5'),
	 ('Fitness 5'),
	 ('Toys 5'),
	 ('Groceries 5'),
	 ('Shoes 5'),
	 ('Accessories 5');
INSERT INTO public.categories ("name") VALUES
	 ('Electronics 6'),
	 ('Clothing 6'),
	 ('Books 6'),
	 ('Home Decor 6'),
	 ('Beauty 6'),
	 ('Fitness 6'),
	 ('Toys 6'),
	 ('Groceries 6'),
	 ('Shoes 6'),
	 ('Accessories 6');
INSERT INTO public.categories ("name") VALUES
	 ('Electronics 7'),
	 ('Clothing 7'),
	 ('Books 7'),
	 ('Home Decor 7'),
	 ('Beauty 7'),
	 ('Fitness 7'),
	 ('Toys 7'),
	 ('Groceries 7'),
	 ('Shoes 7'),
	 ('Accessories 7');
INSERT INTO public.categories ("name") VALUES
	 ('Electronics 8'),
	 ('Clothing 8'),
	 ('Books 8'),
	 ('Home Decor 8'),
	 ('Beauty 8'),
	 ('Fitness 8'),
	 ('Toys 8'),
	 ('Groceries 8'),
	 ('Shoes 8'),
	 ('Accessories 8');
INSERT INTO public.categories ("name") VALUES
	 ('Electronics 9'),
	 ('Clothing 9'),
	 ('Books 9'),
	 ('Home Decor 9'),
	 ('Beauty 9'),
	 ('Fitness 9'),
	 ('Toys 9'),
	 ('Groceries 9'),
	 ('Shoes 9'),
	 ('Accessories 9');
INSERT INTO public.categories ("name") VALUES
	 ('Electronics 10'),
	 ('Clothing 10'),
	 ('Books 10'),
	 ('Home Decor 10'),
	 ('Beauty 10'),
	 ('Fitness 10'),
	 ('Toys 10'),
	 ('Groceries 10'),
	 ('Shoes 10'),
	 ('Accessories 10');
